version: "3"
services:
  
  mongo1:
    hostname: mongo1
    container_name: localmongo1
    image: mongo:4.0-xenial
    ports:
      - "40001:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  
  mongo2:
    hostname: mongo2
    container_name: localmongo2
    image: mongo:4.0-xenial
    ports:
      - "40002:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  
  mongo3:
    hostname: mongo3
    container_name: localmongo3
    image: mongo:4.0-xenial
    ports:
      - "40003:27017"
    restart: always
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "rs0" ]
  
  mongosetup:
    image: mongo:4.0-xenial
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    volumes:
      - ./scripts:/scripts
    restart: "no"
    entrypoint: [ "bash", "/scripts/mongo_setup.sh"]
  
  node1:
    build: ./nodejs
    ports:
      - "81:3000"
  
  node2:
    build: ./nodejs
    ports:
      - "82:3000"
  
  node3:
    build: ./nodejs
    ports:
      - "83:3000"

  rabbitmq-stats:
    image: bitnami/rabbitmq:3.8.14
    container_name: rabbitmq-stats
    volumes:
      - rabbitmq-stats-data:/bitnami
    environment:
      - RABBITMQ_NODE_TYPE=stats
      - RABBITMQ_NODE_NAME=rabbitmq@rabbitmq-stats
      - RABBITMQ_ERL_COOKIE=%U^76CcK
    ports:
      - "40005:15672"

  rabbitmq-queue-one:
    image: bitnami/rabbitmq:3.8.14
    container_name: rabbitmq-queue-one
    depends_on:
      - rabbitmq-stats
    volumes:
      - rabbitmq-queue-one-data:/bitnami
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbitmq@rabbitmq-queue-one
      - RABBITMQ_CLUSTER_NODE_NAME=rabbitmq@rabbitmq-stats
      - RABBITMQ_ERL_COOKIE=%U^76CcK

  rabbitmq-queue-two:
    image: bitnami/rabbitmq:3.8.14
    container_name: rabbitmq-queue-two
    depends_on:
      - rabbitmq-stats
    volumes:
      - rabbitmq-queue-two-data:/bitnami
    environment:
      - RABBITMQ_NODE_TYPE=queue-disc
      - RABBITMQ_NODE_NAME=rabbitmq@rabbitmq-queue-two
      - RABBITMQ_CLUSTER_NODE_NAME=rabbitmq@rabbitmq-stats
      - RABBITMQ_ERL_COOKIE=%U^76CcK

  haproxy:
    image: haproxy:1.7
    volumes:
      - ./rabbitmq/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - rabbitmq-stats
      - rabbitmq-queue-one
      - rabbitmq-queue-two
    ports:
      - 15672:15672
      - 5672:5672

volumes:
  rabbitmq-stats-data:
    driver: local
  rabbitmq-queue-one-data:
    driver: local
  rabbitmq-queue-two-data:
    driver: local